# Generated by Django 4.0.1 on 2022-01-23 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlawxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_content', models.TextField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blawx.workspace')),
            ],
        ),
    ]
