# Generated by Django 4.0.1 on 2022-01-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0002_blawxcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='blawxcode',
            name='scasp_encoding',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blawxcode',
            name='xml_content',
            field=models.TextField(default=''),
        ),
    ]
