# Generated by Django 4.0.1 on 2022-01-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0004_workspace_workspace_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='scasp_encoding',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workspace',
            name='xml_content',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='BlawxCode',
        ),
    ]
