# Generated by Django 4.0.1 on 2022-01-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0005_workspace_scasp_encoding_workspace_xml_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPage',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('path', models.FilePathField(primary_key=True, serialize=False)),
            ],
        ),
    ]
