# Generated by Django 4.0.1 on 2022-01-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0006_docpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docpage',
            name='path',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
