# Generated by Django 4.0.1 on 2022-02-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0007_alter_docpage_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('xml_content', models.TextField(default='')),
            ],
        ),
    ]
