# Generated by Django 4.0.1 on 2022-02-08 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0008_workspacetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='workspace_example',
        ),
    ]
