# Generated by Django 4.0.1 on 2022-02-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0009_remove_workspace_workspace_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='akoma_ntoso',
            field=models.TextField(default=''),
        ),
    ]
