# Generated by Django 4.0.1 on 2022-02-14 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0011_alter_workspace_akoma_ntoso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruledoc_name', models.CharField(max_length=200)),
                ('akoma_ntoso', models.TextField(blank=True, default='')),
                ('scasp_encoding', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RenameField(
            model_name='query',
            old_name='workspace',
            new_name='ruledoc',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='akoma_ntoso',
        ),
        migrations.AddField(
            model_name='query',
            name='xml_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workspace',
            name='ruledoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blawx.ruledoc'),
            preserve_default=False,
        ),
    ]
