# Generated by Django 4.0.1 on 2022-02-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0012_ruledoc_rename_workspace_query_ruledoc_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('ruledoc', 'workspace_name'), name='unique_workspace_and_ruledoc'),
        ),
    ]
