# Generated by Django 4.0.1 on 2022-02-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0013_workspace_unique_workspace_and_ruledoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlawxTest',
            fields=[
                ('workspace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blawx.workspace')),
            ],
            bases=('blawx.workspace',),
        ),
    ]
