# Generated by Django 4.0.1 on 2022-02-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0014_blawxtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlawxTest',
        ),
    ]
