# Generated by Django 4.0.1 on 2022-02-28 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0015_delete_blawxtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlawxTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('xml_content', models.TextField(blank=True, default='')),
                ('scasp_encoding', models.TextField(blank=True, default='')),
                ('ruledoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blawx.ruledoc')),
            ],
        ),
        migrations.AddConstraint(
            model_name='blawxtest',
            constraint=models.UniqueConstraint(fields=('ruledoc', 'test_name'), name='unique_test_and_ruledoc'),
        ),
    ]
