# Generated by Django 4.0.1 on 2022-03-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0016_blawxtest_blawxtest_unique_test_and_ruledoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruledoc',
            name='akoma_ntoso',
        ),
        migrations.AddField(
            model_name='ruledoc',
            name='rule_text',
            field=models.TextField(default='Default Act'),
        ),
    ]
