# Generated by Django 4.0.1 on 2022-06-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0017_remove_ruledoc_akoma_ntoso_ruledoc_rule_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruledoc',
            name='tutorial',
            field=models.TextField(blank=True, default=''),
        ),
    ]
