# Generated by Django 4.0.1 on 2022-07-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0020_ruledoc_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspacetemplate',
            old_name='xml_content',
            new_name='yaml_content',
        ),
    ]
