# Generated by Django 4.0.1 on 2022-07-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0021_rename_xml_content_workspacetemplate_yaml_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkspaceTemplate',
            new_name='RuleDocTemplate',
        ),
    ]
