# Generated by Django 4.0.1 on 2022-07-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0022_rename_workspacetemplate_ruledoctemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RuleDocTemplate',
        ),
    ]
