# Generated by Django 4.0.1 on 2022-07-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0023_delete_ruledoctemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blawxtest',
            options={'permissions': [('run', 'Run Test')]},
        ),
        migrations.AddField(
            model_name='ruledoc',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
