# Generated by Django 4.0.1 on 2022-07-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blawx', '0024_alter_blawxtest_options_ruledoc_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blawxtest',
            name='ruledoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='blawx.ruledoc'),
        ),
    ]
